### PR TITLE
feature: Add Output Stream Docs

### PR DESCRIPTION
**Pull request by alvarowolfx**
The initial structure of Output Stream feature, with the initial implementations:
* Webhooks
* Azure Event Hub
* AWS SQS

Still missing a lot of information, but on this first cut, the focus was documenting the event types using our Protobuf files.

References Protobuf files from API repo: https://github.com/golioth/api/pull/7

### CODE REVIEW

**Comment by beriberikix** [comment]
Great start! Two ideas:

1. It would be easier to read enum values separately, maybe as third column. It could be called "details" and left blank for rows without details
2. Can we prettify the json payload? It's kinda hard to read right now.

**Comment by beriberikix** [comment]
Lookin' good! Do you think "List of Event Types" belong under Reference? I'm okay if we say "yes" but for now it lives under cloud for ease of development.

**Comment by szczys** [comment]
This documentation looks great @alvarowolfx! I mostly made readability edits in my commits but have a couple of things to mention:

- Left sidebars says "AWS SQS -- Coming Soon", should we remove the coming soon?
- I tried out the Azure instructions and added a few screenshots of the process. Let me know what you think. If you like it I can do the same for the AWS instructions
- I have the connection string from Azure, now what do I do with it? Is there a console or CLI process for setting that up?

**Comment by alvarowolfx** [comment]
> * Left sidebars says "AWS SQS -- Coming Soon", should we remove the coming soon?
At first, that was going to launch later, but now we are gonna launch it all together, so I think we can remove it.

> * I tried out the Azure instructions and added a few screenshots of the process. Let me know what you think. If you like it I can do the same for the AWS instructions
Yeah, that looks great, I think we just need to be careful to not show a real credential. I looked at the Azure one and seems like the primary and secondary keys are appearing on the screenshots. 

> * I have the connection string from Azure, now what do I do with it? Is there a console or CLI process for setting that up?
That is going to be used on the Web console, that is still being developed ( probably ready to test early next week ). Right now the only way to register them is by going to the REST API directly. Do you think worth showing hitting the API directly?

**Comment by beriberikix** [comment]
>  Do you think worth showing hitting the API directly?
I don't think so, since it will be extremely uncommon for anyone to use the API directly. I'd say we wait until the UI is ready to document that.

**Comment by szczys** [comment]
> I looked at the Azure one and seems like the primary and secondary keys are appearing on the screenshots.

I deleted that send policy after creating the screenshots so those keys no longer exist. Do you think I still need to remove the keys from the screenshot?

Your nudge made me realize I left the subscription ID in the commit history so I squashed that and also obfuscated the two send keys while I was in there. If you have a local copy, please fetch and reset.

**Comment by alvarowolfx** [comment]
awesome, now I think we can wait for the UI to add some instruction there. Also, we need more content to put on the Output Stream home/overview page, explaining the idea behind it and what users can do with that.

**Pull request merged**
