### PR TITLE
feat: update UI to match new branding

### PR DESCRIPTION
**Pull request by chireia**
Only missing piece is to update all images/screenshots from the old web console

### CODE REVIEW

**Comment by szczys** [comment]
The top of the landing page has "Welcome" instead of a golioth logo/name image. Do we have assets we can use to replicate what is live now with the new logo/colors?
image
image

**Comment by chireia** [comment]
> The top of the landing page has "Welcome" instead of a golioth logo/name image. Do we have assets we can use to replicate what is live now with the new logo/colors? image image

We do, but this was Ariana's request.

**Comment by szczys** [comment]
Changes look great @chireia, thank you!

We discussed a style tweak to footers but once that's ironed out this looks ready for the launch.

**Review by szczys — APPROVED** [review]
LGTM!

**Pull request merged**
