### PR TITLE
fix: update Linux zephyr-sdk install for 0.14.1

### PR DESCRIPTION
**Pull request by szczys**
Updates to docs still needed for MacOS and Windows

### CODE REVIEW

**Comment by szczys** [comment]
Closes #34 
Closes #172

**Comment by szczys** [comment]
@beriberikix I'm not sure this is everything we were thinking for this section. You had mentioned there were some other tools needed (flashing tools maybe?).

**Review by ChrisGammell — APPROVED** [review]
Looks great! Does the Windows version have an update yet? Should that be added here?

**Comment by beriberikix** [comment]
Ah yes, Windows & macOS are supported in the [new SDK release](https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.14.1). I've tested both. They still don't have Host tools, unfortunately. That means debug and flash may not work out of the box for every platform.

The also introduced a nice enhancement in the form of a "minimal" bundle, that lets you only download the tools for the platforms you care about, which can be a significant savings. More complicated but useful pro tip.

**Comment by ChrisGammell** [comment]
OK, Mike said he would try the Windows version. 

@beriberikix can you help him since you have tried this once?

**Comment by szczys** [comment]
@beriberikix and I worked through the windows install together and it looks good.

I'd like to merge this PR and next do a restructuring of where we place and  how we name the partials for this process. It has become unmaintainable and this will pave the way to use one set of partials for multiple install paths (zephyr sdk versus ncs sdk).

**Review by ChrisGammell — APPROVED** [review]
Looks good!

**Pull request merged**
