### PR TITLE
Brand updates: color palette and font

### PR DESCRIPTION
**Pull request by szczys**
Clean up the brand updates:

* Normalize custom css colors to use new Golioth color palette
* Use Akkarat font

### CODE REVIEW

**Review by ChrisGammell — COMMENTED** [review]
Colors look great, might want to consider Akkurat light for the content?

**Comment by ChrisGammell** [comment]
Ahh, nm, we change the font weight on headlines on the main site, but it's not the "light" version of the font.

**Review by ChrisGammell — APPROVED** [review]
Checked on font, LGTM

**Comment by szczys** [comment]
Since I already have everything set up, here are screenshots for Light, Regular (what was merged), and Black versions of the font.
Screenshot 2023-11-25 at 16-58-34 What is Golioth Golioth

Screenshot 2023-11-25 at 16-58-48 What is Golioth Golioth

Screenshot 2023-11-25 at 16-59-38 What is Golioth Golioth

**Pull request merged**
