### PR TITLE
feat: Add CoAP/MQTT interface docs

### PR DESCRIPTION
**Pull request by alvarowolfx**
I probably will need some help on how to fill some gaps when talking about use cases per protocol, talk about security related to credentials and etc.

### CODE REVIEW

**Comment by vitprajzler** [comment]
The links in the Overview page point to non-existent pages

**Comment by alvarowolfx** [comment]
> The links in the Overview page point to non-existent pages

@vitprajzler not sure how this happened because Docusaurus fails to build with broken links and depending on where you start the navigation it was working here. 

Anyway, I moved to the reference section per @beriberikix suggestion and I changed the links on the overview page to not be relative.

https://golioth-docs-dev--pr85-feature-coap-mqtt-in-ng8drg3o.web.app/reference/protocols/overview/

**Comment by beriberikix** [comment]
Did you plan to REST API section to reference as well?

**Comment by alvarowolfx** [comment]
> Did you plan to REST API section to reference as well?

Just pushed a change to move to the reference section.

**Pull request merged**
